jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Generate metrics
        run: npm run generate

      - name: Commit metrics (or create pull request)
        uses: actions/upload-artifact@v2
        with:
          name: metrics-image
          path: metrics.svg

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          
      - name: Handle output action
        run: |
          # This is where you specify how the image should be handled
        with:
          output_action: pull  # or 'gist' or 'none'
          github_token: ${{ secrets.METRICS_TOKEN }}  # Make sure to pass the token
